name: 'Login to GHCR Action'
description: 'Login to GitHub Container Registry'

runs:
  using: 'composite'
  steps:

    - name: 'Login to GitHub Container Registry'
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}

    - id: string
      uses: ASzc/change-string-case-action@v5
      with:
        string: ${{github.repository}}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          ghcr.io/${{ steps.string.outputs.lowercase }}:${{ env.UPCOMING_CHART_VERSION }}
          ghcr.io/${{ steps.string.outputs.lowercase }}:latest
