name: 'Go Action'
description: 'Set up Go, run test and build'

runs:
  using: 'composite'
  steps:
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.17
        cache: false

    - name: Run tests
      run: go test ./...

    - name: Build Go project
      run: go build -o myapp


