name: 'Create and Push Tag Action'
description: 'Create and push tag'

runs:
  using: 'composite'
  steps:
    - name: Create and push tag
      shell: bash
      run: |
        git tag ${{ env.NEW_RELEASE_VERSION }}
        git push origin ${{ env.NEW_RELEASE_VERSION }}
