name: Build, Test, and Versioning

on:
  push:
    branches:
      - master

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: ./.github/actions/checkout-action.yml

      - name: Go test build
        uses: ./.github/actions/test-build-go-action.yml

      - name: Update version
        uses: ./.github/actions/version-action.yaml

      - name: Commit and push changes
        uses: ./.github/actions/commit-push-action.yaml

      - name: 'Login to GitHub Container Registry'
        uses: ./.github/actions/build-push-docker-action.yaml

      - name: Create and push tag
        uses: ./.github/actions/create-push-tag-action.yaml

