name: Build, Test, and Versioning

on:
  push:
    branches:
      - master


permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Go test build
        uses: ./.github/actions/test-build-go-action

      - name: Update version
        uses: ./.github/actions/version-update-action

      - name: Commit and push changes
        uses: ./.github/actions/commit-push-action

      - name: 'Login to GitHub Container Registry'
        uses: ./.github/actions/build-push-docker-action
        with:
          password : ${{ secrets.GITHUB_TOKEN }}
          username: ${{ github.actor }}
          repository: ${{ github.repository }}

      - name: Create and push tag
        uses: ./.github/actions/create-push-tag-action

